### ISSUE TITLE
Co-op Fix isn't working in v28.1.4590

### ISSUE THREAD

**Issue by seanvanpelt2** [Timotheeee/btd6_mods#14]
So I used your custom_maps_v2 awhile ago in a previous version and I finally learned about your co-op fix, but when I tried it, nothing changed and I still have the same error.

When using the co-op fix it was the only mod installed.

Also you probably know what the error is, but I'll put it here anyways.
"NKMulti message too big - code: , 34695 bytes"

**Comment by Timotheeee** [comment]
it never actually worked for anyone, it was more of an experiment to see if it would fix the problem.

**Comment by seanvanpelt2** [comment]
So I just have to reset my progress or never play multiplayer again?

**Comment by Timotheeee** [comment]
> So I just have to reset my progress or never play multiplayer again?

yeah, that's why you should use an alt account to play with mods
