### ISSUE TITLE
Missing dll file for btd6Ai and btd6AILategame

### ISSUE THREAD

**Issue by v00d0079** [Timotheeee/btd6_mods#18]
Hey just wanted to let you know there isnt currently a dll file for either of these mods and this means they cannot be run. If I'm mistaken on that fact please let me know I'd love to mess around with the ai a bit

**Comment by thegreeen** [comment]
> Hey just wanted to let you know there isnt currently a dll file for either of these mods and this means they cannot be run. If I'm mistaken on that fact please let me know I'd love to mess around with the ai a bit

You need to compile this Mod for your self, meaning you need to:
1. Have Visual Studio installed
2. Open the .sln file
3. On the to left click on build and choose "build btd6ai"
4. Then you have the dll for the mods folder
