### ISSUE TITLE
bloon_customizer and tower_customizer do not save original. and custom_rounds do not load

### ISSUE THREAD

**Issue by PrismaAce** [Timotheeee/btd6_mods#24]
![image](https://user-images.githubusercontent.com/77484747/168410032-092c5614-f72f-453f-8fcb-e4a2be0811c8.png)

for testing, i replaced the Red on round 1 with Rainbow, used shift+f2 to load (log outputted that they were loaded) and they were still reds, i tried restarting the game and everything but nothing changed

**Comment by Timotheeee** [comment]
I suggest not downloading mods from github directly, and instead using the mod download channel on the discord server as it is better maintained.
