### ISSUE TITLE
How do you unlock custom maps?

### ISSUE THREAD

**Issue by UpTwoSpeed** [Timotheeee/btd6_mods#30]
It said to press f9 and restart the game but it isn't working

**Comment by UltraBlackLinux** [comment]
Same here. No info about it whatsoever, nothing happens either

**Comment by Timotheeee** [comment]
"to unlock the maps **go into a game**, press f9"

**Comment by UltraBlackLinux** [comment]
> "to unlock the maps **go into a game**, press f9"

guess what's not working
