### ISSUE TITLE
Turrets stuck at 0/0/0

### ISSUE THREAD

**Issue by RunsFire** [Timotheeee/btd6_mods#37]
Sometimes when I upgrade my tower, it becomes a 0/0/0 tower (dart monkey for the majority of the time), and it won't change after an other upgrade or even after a return to home screen and coming back into the map.
![image](https://user-images.githubusercontent.com/104054744/184686409-8acb24f6-0b25-4c76-9d4d-65c74585f567.png)
(same turret for the second image, just "upgraded" it a little)
![image](https://user-images.githubusercontent.com/104054744/184686510-4e1be716-1731-4933-9dff-f371c7ea55b8.png)

**Comment by Timotheeee** [comment]
custom tower mods sometimes break the randomizer

**Comment by RunsFire** [comment]
I don't have any mods that add custom towers. The only mod that can, I think, have a probability to break this mod is ultimate crosspathing, but I doubt that as I saw a video of ISAB who had the two with no issue ...

**Comment by Timotheeee** [comment]
> I don't have any mods that add custom towers. The only mod that can, I think, have a probability to break this mod is ultimate crosspathing, but I doubt that as I saw a video of ISAB who had the two with no issue ... (my mods : multi-cash; sacrifice helper; speedhackmelon; ultimate crosspathing; unlimited 5th tiers+; and, of course, balanced random towers)

I just tested it with ultimate crosspathing and it works fine. Make sure you are using the newest version by redownloading it. also you can check the console to see the value of the new tower after upgrading.

**Comment by RunsFire** [comment]
Ok, so it seems this bug is pretty random :
- For the value is the console, it just says "new value : 216"
- Most of the time, it is locked in dart monkey. However, it seems it can also change (glue, tack, sub ..) but it always stays very low tier (can sometimes have some upgrade that disappear when you upgrade it an other time), and this doesn't change even if you upgrade it 100 times (see image) 
![image](https://user-images.githubusercontent.com/104054744/185594205-23cf023e-4919-4c02-ae3a-0e991325af1a.png)
- It is very random : on some games, you can have it on every tower you place, and in other game you'll have no issue, even after 100+ round
- Lastly, for the version, I downloaded it like 5 times, here on github or in game with the mod helper, and doesn't change anything.

PS : I can also just be super dumb and I miss one file (I have the .dll in my mods folder does I need something else ?)

**Comment by RunsFire** [comment]
Oh, and I didn't see before, but seems like the name in the tower IG are wrong and updates really rarely (when the bug occurs)
![image](https://user-images.githubusercontent.com/104054744/185596259-68c0c58d-c292-43de-8622-4f6540fde636.png)
![image](https://user-images.githubusercontent.com/104054744/185596309-ef17f140-e22a-4f2f-a6c8-55b2727bd0ec.png)

**Comment by RunsFire** [comment]
Seems to be resolved with the latest version, so I'm closing this issue ! for the moment, that is .... (and I hope forever)
